/**
 * formatter.js
 * Builds the final Markdown or XML output string from collected files.
 */

// ── Token-saver: content minifier ────────────────────────────────────────────

/**
 * Strip comments and blank lines from source content.
 * Handles: // line comments, /* block comments *\/, <!-- HTML comments -->,
 * # shell/python line comments, and consecutive blank lines.
 *
 * Intentionally conservative — only removes patterns that are unambiguously
 * comments so we don't mangle string literals or template syntax.
 *
 * @param {string} content  Raw file content
 * @param {string} lang     Language identifier (e.g. 'javascript', 'python')
 * @returns {string}        Minified content
 */
function minifyContent(content, lang = '') {
  let result = content;

  // Block comments: /* ... */ (JS, CSS, Java, C, Go, Rust, …)
  // The [^*] guard avoids stripping /*! license banners partially, but we
  // keep it simple and remove all of them for token savings.
  if (/^(javascript|jsx|typescript|tsx|css|scss|sass|less|java|kotlin|swift|go|rust|c|cpp|csharp|scala|php)$/.test(lang)) {
    result = result.replace(/\/\*[\s\S]*?\*\//g, '');
  }

  // Line comments: // … (same language set)
  if (/^(javascript|jsx|typescript|tsx|java|kotlin|swift|go|rust|c|cpp|csharp|scala|php)$/.test(lang)) {
    result = result.replace(/^\s*\/\/.*$/gm, '');
  }

  // HTML / XML comments: <!-- … -->
  if (/^(html|xml|xhtml|vue|svelte|markdown|mdx)$/.test(lang)) {
    result = result.replace(/<!--[\s\S]*?-->/g, '');
  }

  // Hash line comments: # … (Python, Ruby, Shell, YAML, TOML, …)
  if (/^(python|ruby|bash|yaml|toml|dockerfile|)$/.test(lang) || lang === '') {
    // Only strip lines where # is the first non-whitespace character
    // to avoid nuking colour codes, markdown headings, etc.
    result = result.replace(/^\s*#.*$/gm, '');
  }

  // Collapse 2+ consecutive blank lines into a single blank line
  result = result.replace(/\n{3,}/g, '\n\n');

  // Trim trailing whitespace on every line
  result = result.replace(/[ \t]+$/gm, '');

  return result.trim();
}

/**
 * Produce an LLM-optimised Markdown document.
 *
 * Structure:
 *   # Codebase Context
 *   ## Project Structure
 *   ```
 *   <tree>
 *   ```
 *   ## Files
 *   ### <relative path>
 *   ```<lang>
 *   <content>
 *   ```
 */
export function buildMarkdown(collected, options = {}) {
  const { includeTree = true, minify = false } = options;
  const { files, tree } = collected;

  const parts = [];

  parts.push('# Codebase Context');
  parts.push(`\n> Generated by **ai-context-packer** · ${files.length} file(s) included${minify ? ' · minified' : ''}\n`);

  if (includeTree) {
    parts.push('## Project Structure\n');
    parts.push('```\n' + tree + '\n```\n');
  }

  parts.push('## Files\n');

  for (const file of files) {
    parts.push(`### \`${file.relativePosix}\`\n`);
    const fence = '```' + (file.lang || '');
    const content = minify ? minifyContent(file.content, file.lang) : file.content;
    parts.push(`${fence}\n${content}\n\`\`\`\n`);
  }

  return parts.join('\n');
}

/**
 * Produce an LLM-optimised XML document.
 *
 * Structure:
 *   <codebase>
 *     <project_structure>...</project_structure>
 *     <files>
 *       <file path="...">
 *         <![CDATA[ ... ]]>
 *       </file>
 *     </files>
 *   </codebase>
 */
export function buildXML(collected, options = {}) {
  const { includeTree = true, minify = false } = options;
  const { files, tree } = collected;

  const lines = [];

  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push(`<!-- Generated by ai-context-packer${minify ? ' | minified' : ''} -->`);
  lines.push(`<codebase file_count="${files.length}">`);

  if (includeTree) {
    lines.push('  <project_structure>');
    lines.push('<![CDATA[');
    lines.push(tree);
    lines.push(']]>');
    lines.push('  </project_structure>');
  }

  lines.push('  <files>');

  for (const file of files) {
    const lang = file.lang ? ` lang="${file.lang}"` : '';
    lines.push(`    <file path="${escapeXmlAttr(file.relativePosix)}"${lang}>`);
    lines.push('<![CDATA[');
    const content = minify ? minifyContent(file.content, file.lang) : file.content;
    lines.push(content.replace(/]]>/g, ']]]]><![CDATA[>'));
    lines.push(']]>');
    lines.push('    </file>');
  }

  lines.push('  </files>');
  lines.push('</codebase>');

  return lines.join('\n');
}

/** Escape characters that are invalid in XML attribute values. */
function escapeXmlAttr(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}
